In [1]:
import torch
import numpy as np
import pandas as  pd

#Obtendo Informações

In [2]:
# import gdown

# #Realizando download dos dados do Google Drive
# !gdown --id '1-6yFjS0yOXFxFSZb6sOJlgxOklqQRuLu'

In [3]:
# #Descompactando dataset para a raiz do notebook
# !unzip /content/features.zip

In [2]:
# Load Torch Data
test_embeds = torch.load('save/linear/path_models/path_lr_0.0001_bsz_32_SINCERE/embeds.pth', weights_only=False)
test_labels = torch.load('save/linear/path_models/path_lr_0.0001_bsz_32_SINCERE/labels.pth', weights_only=False)
print(test_embeds.shape, test_labels.shape)

torch.Size([10896, 2048]) torch.Size([10896])

#Observando os espaços de características

##Projeção Multidimensional (t-SNE)

Documentation: https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html

In [3]:
from sklearn.manifold import TSNE

In [4]:
X = np.array(test_embeds)
X_embedded = TSNE(n_components=2, learning_rate='auto', init='random', perplexity=25).fit_transform(X)
X_embedded.shape

/tmp/ipykernel_1477743/1109792787.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  X = np.array(test_embeds)

(10896, 2)

In [5]:
df_y  = pd.DataFrame(test_labels)
df_X  = pd.DataFrame(X_embedded)
df_Xy = pd.concat([df_X, df_y], axis=1)
df_Xy.columns = ["x", "y", "Class"]
df_Xy[0:5]

           x          y  Class
0  -0.243614  26.185230    0.0
1  30.121645  10.493479    0.0
2 -71.906525  10.143188    0.0
3 -12.109063  79.286812    0.0
4  -1.527220  21.836435    0.0

In [6]:
import plotly.express as px
fig = px.scatter(df_Xy, x="x", y="y", color="Class", height=600, width=1200)
fig.show()

##Projeção Multidimensional (PCA)

Documentation: https://scikit-learn.org/dev/modules/generated/sklearn.decomposition.PCA.html

In [9]:
from sklearn.decomposition import PCA

In [10]:
X = np.array(test_embeds)
X_embedded = PCA(n_components=2).fit_transform(X)
X_embedded.shape

/tmp/ipykernel_1423043/234629355.py:1: DeprecationWarning:

__array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.

(10896, 2)

In [11]:
df_y  = pd.DataFrame(test_labels)
df_X  = pd.DataFrame(X_embedded)
df_Xy = pd.concat([df_X, df_y], axis=1)
df_Xy.columns = ["x", "y", "Class"]
df_Xy[0:5]

          x         y  Class
0 -1.212887  1.605779    0.0
1  0.369338  0.693545    0.0
2  0.207894  1.579652    0.0
3 -2.254835 -0.040553    0.0
4 -0.673436  1.474415    0.0

In [12]:
import plotly.express as px
fig = px.scatter(df_Xy, x="x", y="y", color="Class", height=600, width=1200)
fig.show()

##Projeção Multidimensional (MDS)

Documentation: https://scikit-learn.org/dev/modules/generated/sklearn.manifold.MDS.html

In [ ]:
from sklearn.manifold import MDS
from sklearn.metrics.pairwise import cosine_distances

:

In [ ]:
X = np.array(test_embeds).astype(np.float64)
X_embedded = MDS(n_components=2, dissimilarity='euclidean', normalized_stress='auto').fit_transform(X)
# dissimilarities = cosine_distances(X)
# X_embedded = MDS(n_components=2, dissimilarity='precomputed', normalized_stress='auto').fit_transform(dissimilarities)
X_embedded.shape

/tmp/ipykernel_1423043/663370613.py:1: DeprecationWarning:

__array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.

In [ ]:
df_y  = pd.DataFrame(test_labels)
df_X  = pd.DataFrame(X_embedded)
df_Xy = pd.concat([df_X, df_y], axis=1)
df_Xy.columns = ["x", "y", "Class"]
df_Xy[0:5]

          x         y  Class
0  0.888598  0.395299    1.0
1  0.566601 -0.773885    2.0
2 -0.653902 -0.711553    7.0
3 -0.915753  0.051033    9.0
4  0.145409  0.783022    6.0

In [ ]:
import plotly.express as px
fig = px.scatter(df_Xy, x="x", y="y", color="Class", height=600, width=1200)
fig.show()